theme: jekyll-theme-minimal

highlighter: rouge


title: EMDAD HAQUE
description: This is a showcase of my career profile and recent projects I have worked on and documented.
logo: ./assets/img/emdad-profile.jpeg
show_downloads: false
