theme: jekyll-theme-minimal

title: EMDAD HAQUE
description: Summary of my career goals, experiences, projects, specialties and interests.
logo: ./assets/img/LinkedIn-Photo.jpeg
show_downloads: false
