theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


title: EMDAD HAQUE
description: ABOUT ME
logo: ./assets/img/LinkedIn-Photo.jpeg
show_downloads: false
